# Generated by Django 5.1.6 on 2025-03-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('injury', models.TextField()),
                ('detailed_plan', models.TextField()),
                ('estimated_RTC', models.DateField()),
                ('trainer_name', models.CharField(max_length=64)),
            ],
        ),
    ]
