# Generated by Django 5.1.6 on 2025-03-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_appointment_traineravailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(default='treatment', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='athlete_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='trainer_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='traineravailability',
            name='trainer_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='traineravailability',
            name='trainer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
