# Generated by Django 5.1.6 on 2025-03-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineravailability',
            name='trainer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
