# Generated by Django 5.1.6 on 2025-04-15 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_appointment_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentplan',
            name='estimated_RTC',
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=14)),
        ),
    ]
