# Generated by Django 5.1.6 on 2025-04-01 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
        ('trainers', '0004_appointment_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('restricted', 'Restricted'), ('out', 'Out')], default='healthy', max_length=10)),
                ('trainer_restrictions', models.TextField(default='No Restrictions', max_length=500)),
                ('estimated_RTC', models.DateField(default=None, null=True)),
                ('athlete_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('treatment_plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.treatmentplan')),
            ],
        ),
    ]
