# Generated by Django 5.1.6 on 2025-04-14 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_athletestatus'),
        ('trainers', '0004_appointment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletestatus',
            name='treatment_plan_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainers.treatmentplan'),
        ),
    ]
