# Generated by Django 5.1.6 on 2025-04-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_alter_athletestatus_treatment_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletestatus',
            name='date_of_injury',
            field=models.DateField(default=None, null=True),
        ),
    ]
