# Generated by Django 5.1.6 on 2025-04-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_athletestatus_date_of_injury'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletestatus',
            name='injury',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
