# Generated by Django 5.1.6 on 2025-04-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0005_athletestatus_injury'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athletestatus',
            name='treatment_plan_id',
        ),
        migrations.AddField(
            model_name='athletestatus',
            name='detailed_plan',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='athletestatus',
            name='trainer_name',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
